apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbit-hpa-manager
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "watch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rabbit-hpa-manager-binding
subjects:
  - kind: ServiceAccount
    name: rabbitmq-operator-controller-manager
    namespace: rabbitmq-operator-system
roleRef:
  kind: ClusterRole
  name: rabbit-hpa-manager
  apiGroup: rbac.authorization.k8s.io
